# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

#https://docs.travis-ci.com/user/deployment/heroku/
deploy:
  provider: heroku
  api_key:
    secure: "29YGhjOdbGoQvkMWnUA0OhGfR+utdgBNwBJsyYFMY4nrJNyfDv89uPQUlQ/DT1F7Fsiyxo98e438UQ50COjcczGejesv2jlE29MvtaK42hGequOCOyaj478njTrOjqCqgO8Wie0xq072fKHkwPMhPYSkVO4390MeAKK3+E4htXacWR/qO/bGG5gLIfDC3gXp0TQ9bdA3adwqY/m1CuLDx5e6ITZip4DUt0yJP7dogtTWQ9E3yk0SSUVHqLz+zQWYLs1WlVBQneGqBNpKMCIAvZV1CoGm+NJoLRgi2NZwJ2++1sEscZAIpX23QKlpZ4eW/Bm36fdzEo4hXHW4d7VfI6v9yzn+7KE9MiQh3Pw8PHf1Qa0hwAdxRtr5goxds3TlM/wTUmR3U7OytvmcL/fg2VQzTEDtvlyV714h6D6N9ixYO52CXc+rGXdYirOZUpv2lvs16pk7Ww4jbg7uHyZs4PXM1qftsZMOniFFKnkjJKoZsR9/hCOvev5KYXdb8AUrJ22uMal8sLTZtiKIKY/amH+tGCEFIkwMk3lfF992LQMjOcvSQPbGYtv8+EqEK0dYRtIYl9DJoisNjb7g1dF5gwTkxia0cRWRntcrd1a5Wq2VJVRQiPnZ8Y/488Cn8EG/TbYswY15fDRtATycgwEX55AmbfDRgj7DOawo6LL7dOA="