# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: oraclejdk8

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

#https://docs.travis-ci.com/user/deployment/heroku/
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY